### ISSUE TITLE
训练报错,根pytorch的版本有关

### ISSUE THREAD

**Issue by cqray1990** [lcy0604/EraseNet#19]
pytorch 1.13.1
cuda11.6

Traceback (most recent call last):
  File "/EraseNet/train_STE.py", line 109, in <module>
    G_loss.backward()
  File /.conda/envs/paddle_env/lib/python3.9/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File ".conda/envs/paddle_env/lib/python3.9/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [1, 512, 4, 4]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by lanfen100** [comment]
> pytorch 1.13.1 cuda11.6
> 
> Traceback (most recent call last): File "/EraseNet/train_STE.py", line 109, in G_loss.backward() File /.conda/envs/paddle_env/lib/python3.9/site-packages/torch/_tensor.py", line 488, in backward torch.autograd.backward( File ".conda/envs/paddle_env/lib/python3.9/site-packages/torch/autograd/**init**.py", line 197, in backward Variable._execution_engine.run_backward( # Calls into the C++ engine to run the backward pass RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [1, 512, 4, 4]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

提高pytorch版本后报这个错，你这边后来解决了么， 代码改怎么修改， 先感谢您的回答。
