### ISSUE TITLE
Size mismatch error

### ISSUE THREAD

**Issue by EricStarer** [lcy0604/EraseNet#4]
Anyone met the same problem？
`Traceback (most recent call last):
  File "train_STE.py", line 105, in <module>
    x_o1,x_o2,x_o3,fake_images,mm = netG(imgs)
  File "/data1/xing_zhao/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data1/xing_zhao/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 167, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/data1/xing_zhao/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 177, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/data1/xing_zhao/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/data1/xing_zhao/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/data1/xing_zhao/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/data1/xing_zhao/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/DeepLearning/xing_zhao/inpainting/EraseNet-master/models/sa_gan.py", line 203, in forward
    x = torch.cat([self.lateral_connection3(con_x2), x], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 2. Got 32 and 31 (The offending index is 0)
`

**Comment by EricStarer** [comment]
the input size problem
