### ISSUE TITLE
Inplace operation error

### ISSUE THREAD

**Issue by EricStarer** [lcy0604/EraseNet#5]
Any one met the same problem?
`  warnings.warn('Was asked to gather along dimension 0, but all '
Traceback (most recent call last):
  File "train_STE.py", line 109, in <module>
    G_loss.backward()
  File "/data1/xing_zhao/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/data1/xing_zhao/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 512, 4, 4]], which is output 38 of BroadcastBackward, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
`

**Comment by EricStarer** [comment]
I use pytorch 1.3.1 and the problem is done.
