### ISSUE TITLE
Multi GPU training error

### ISSUE THREAD

**Issue by heping0307** [lcy0604/EraseNet#7]
Has anyone encountered such a mistake? When I replace a single GPU with multiple GPUs, I can't run.

THCudaCheck FAIL file=/tmp/pip-req-build-4baxydiv/aten/src/THCUNN/generic/LeakyReLU.cu line=56 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "/lustre/home/phe/windows_pycharmProjects/EraseNet-master/train_STE.py", line 106, in <module>
    G_loss = criterion(imgs, masks, x_o1, x_o2, x_o3, fake_images, mm, gt, count, i)
  File "/lustre/home/phe/miniconda3/envs/erasenet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/lustre/home/phe/miniconda3/envs/erasenet/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/lustre/home/phe/miniconda3/envs/erasenet/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/lustre/home/phe/miniconda3/envs/erasenet/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/lustre/home/phe/miniconda3/envs/erasenet/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/lustre/home/phe/miniconda3/envs/erasenet/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/lustre/home/phe/miniconda3/envs/erasenet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/lustre/home/phe/windows_pycharmProjects/EraseNet-master/loss/Loss.py", line 60, in forward
    D_loss.backward(retain_graph=True)
  File "/lustre/home/phe/miniconda3/envs/erasenet/lib/python3.7/site-packages/torch/tensor.py", line 166, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/lustre/home/phe/miniconda3/envs/erasenet/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: an illegal memory access was encountered

**Comment by XiaoCode-er** [comment]
@heping0307 遇到了相同的问题，解决了嘛？
